services:
 web:
  image: nginx
  restart: always
  secret:
    - secret
  volumes:
    - ~/data/wordpress
  ports:
      - "443"
 db:
  image: mariadb
  restart: always
  secret:
    -secret
  volumes:
    - ~/data/wordpress
 site:
  image: wordpress
  restart: always
  ports:
    - port
  secret:
    -secret
  volumes:
    - ~/data/wordpress

