services:
 web:
  image: nginx
  restart: always
  volumes:
    - ~/data/wordpress
  ports:
    - "443:443"
 db:
  image: mariadb
  restart: always
  secret:
    -secret
  volumes:
    - ~/data/wordpress:/var/www/html
wordpress:
  image: wordpress
  restart: always
  ports:
    - port
  secret:
    -secret
  volumes:
    - ~/data/wordpress

