services:
 nginx:
  build: requirements/nginx
  depends_on:
   -  wordpress
  container_name: nginx
  networks:
   - inception
  env_file: .env
  restart: always
  volumes:
   - wordpress:/var/www/html 
  ports:
   - 443:443
 mariadb:
  build: requirements/mariadb
  container_name: mariadb
  networks:
   - inception
  env_file: .env
  restart: on-failure
  volumes:
   - mariadb:/var/lib/mysql
 wordpress:
  build: requirements/wordpress 
  depends_on:
   -  mariadb
  container_name: wordpress
  networks:
   - inception
  env_file: .env
  restart: on-failure
  volumes:
   - wordpress:/var/www/html 

networks:
 inception:
  driver: bridge

volumes:
 wordpress:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: ~/data/wordpress
 mariadb:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: ~/data/mariadb
  
