services:
 mginx:
  build: requirements/nginx
  container_name: nginx
  networks:
   - inception
  env_file: .env
  restart: always
  volumes:
   - ~/data/wordpress:/data/www
  ports:
   - "443:443"
 mariadb:
  build: requirements/mariadb
  container_name: mariadb
  networks:
   - inception
  env_file: .env
  restart: on-failure
  volumes:
   - ~/data/mariadb:/var/lib/mariadb
 wordpress:
  build: requirements/wordpress 
  depends_on:
   -  mariadb
  container_name: wordpress
  networks:
   - inception
  env_file: .env
  restart: on-failure
  volumes:
   - ~/data/wordpress:/data/www

networks:
 inception:
  driver: bridge
